branch-defaults:
  master:
    environment: instant-chat-ui-dev
    group_suffix: null
environment-defaults:
  instant-chat-ui:
    branch: null
    repository: null
global:
  application_name: instant-chat-ui
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 17.03.1-ce
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
